# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colaboratory.

Original file is located at

    https://colab.research.google.com/drive/1B4azVxDV47C6FmYICPYQ9A38d461rFTw

    https://colab.research.google.com/drive/1BYj_U3sRkT7ZxXcj8sceklYoWDumo2pQ

"""

score = input().split()
count = 0
count1 = 0
for i in score:
  if int(i) < 60:

    count += 1
print("不及格人數; ",count)
Max = 0
Min = 100
for i in score:
  if int(i) < Min:
    Min = int(i)
  if int(i) > Max:
    Max = int(i)
print("最高分：",Max,"最低分：",Min)

sum = 0
for i in score:
  sum += int(i)
  count1 += 1
average = sum/count1
print("平均數", average)

