# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BYj_U3sRkT7ZxXcj8sceklYoWDumo2pQ
"""

score = input().split()
countF = 0
count = 0
for i in score:
  if int(i) < 60:
    print(i)
    countF += 1
print("不及格人數", countF)

sum = 0
for i in score:
  sum += int(i)
  count += 1
average = sum/count
print("平均數", average)